apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: hello
    tier: backend
    track: stable
  ports:
    - protocol: TCP
      port: 8080  # Example port used by the backend service
      targetPort: 8080  # Example target port used by the backend service
